version: '3.2'
services:
  nginx:
    image: casa-manager:5000/nginx-mod
      #volumes:
      #- './nginx.conf:/etc/nginx/nginx.conf'
      # - 'nginx_vol:/etc/nginx/error_log.log'
        #- 'nginx_cache_vol:/etc/nginx/cache'
        #- /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    expose:
      - 80
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: '1234'
    volumes:
      - 'pihole_vol:/etc/pihole'
    restart: unless-stopped

volumes:
  pihole_vol:
    driver_opts:
      type: "nfs"
      o: "addr=nas-casa.local,nolock,soft,rw"
      device: ":/export/pihole/"
  nginx_vol:
    driver_opts:
      type: "nfs"
      o: "addr=nas-casa.local,nolock,soft,rw"
      device: ":/export/nginxRP/"
