version: "3"
services:
  registry:
    image: registry:latest
    ports:
      - 5000:5000
    volumes:
      - 'registry_vol:/var/lib/registry'
    restart: unless-stopped

volumes:
  registry_vol:
    driver_opts:
      type: "nfs"
      o: "addr=nas-casa.local,nolock,soft,rw"
      device: ":/export/casa-registry/"
