---
- name: Verify and register worker join token
  debug:
    msg: "{{ lookup('file', 'tmp/worker_token') }}"

- name: Join worker to swarm
  become: True
  become_method: sudo
  community.docker.docker_swarm:
    state: join
    join_token: "{{ lookup('file', 'tmp/worker_token') }}"
    remote_addrs: "{{ lookup('file', 'tmp/first_manager_name') }}"

