---
- name: Update and upgrade apt packages
  become: true
  become_method: sudo
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Install packages to common
  become: true
  become_method: sudo
  apt:
    pkg:
      - vim
      - ansible
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
      - gnupg-agent
      - aptitude
      - docker.io
      - docker-compose
      - nfs-common
    state: latest

- name: Ignore PEP 668 because it's silly.
  become: true
  become_method: sudo
  ansible.builtin.file:
    path: /usr/lib/python3.11/EXTERNALLY-MANAGED
    state: absent

- name: Install pip packages to all
  ansible.builtin.pip:
    name:
      - jsondiff

- name: Add docker group
  become: true
  become_method: sudo
  group:
    name: "docker"
    state: present

- name: Add mugsy to docker group
  become: true
  become_method: sudo
  user:
    name: mugsy
    groups: docker
    append: yes

- name: copy docker daemon config to hosts
  become: true
  become_method: sudo
  ansible.builtin.copy:
    src: roles/common/configs/daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'

- name: Ensure docker is running and enabled at boot
  become: true
  become_method: sudo
  systemd:
    name: "docker.service"
    state: started
    enabled: true

- name: Ensure containerd is running and enabled at boot
  become: true
  become_method: sudo
  systemd:
    name: "containerd.service"
    state: started
    enabled: true

- name: Check if public key exists
  stat:
    path: "~/.ssh/id_rsa.pub"
  register: pubkey

- name: Create public private keypair
  community.crypto.openssh_keypair:
    path: ~/.ssh/id_rsa
  when: not pubkey.stat.exists

- name: Add ssh trusts
  authorized_key:
    user: "mugsy"
    state: present
    key: "{{ vozdukh_pub }}"
