---
- name: Update and upgrade apt packages
  become: true
  become_method: sudo
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Install packages to common
  become: true
  become_method: sudo
  apt:
    pkg:
      - vim
      - ansible
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
      - gnupg-agent
      - aptitude
      - docker.io
      - docker-compose
    state: latest

- name: Add docker group
  become: true
  become_method: sudo
  group:
    name: "docker"
    state: present

- name: Add mugsy to docker group
  become: true
  become_method: sudo
  user:
    name: mugsy
    groups: docker
    append: yes
