version: '3'
services:
  mediamtx:
    image: bluenviron/mediamtx:latest-ffmpeg-rpi
    container_name: mediamtx
    network_mode: host  # Recommended
    environment:
      - "MTX_PATHS_CAM_SOURCE=rpiCamera"
    devices:
      - /dev/media0:/dev/media0
      - /dev/media1:/dev/media1
      - /dev/media2:/dev/media2
      - /dev/media3:/dev/media3
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12
      - /dev/video13:/dev/video13
      - /dev/video14:/dev/video14
      - /dev/video15:/dev/video15
      - /dev/video16:/dev/video16
      - /dev/video18:/dev/video18
      - /dev/video20:/dev/video20
      - /dev/video21:/dev/video21
      - /dev/video22:/dev/video22
      - /dev/video23:/dev/video23
      - /dev/video31:/dev/video31
      - /dev/v4l-subdev0:/dev/v4l-subdev0
      - /dev/dma_heap:/dev/dma_heap
    volumes:
      - /run/udev:/run/udev:ro
      - ./mediamtx.yml:/mediamtx.yml
    tmpfs:
      - /dev/shm:exec
    restart: unless-stopped
