---
- name: Verify and register manager join token
  debug:
    msg: "{{ lookup('file', 'tmp/manager_token') }}"

- name: Join managerto swarm
  community.docker.docker_swarm:
    state: join
    join_token: "{{ lookup('file', 'tmp/manager_token') }}"
    remote_addrs: "{{ lookup('file', 'tmp/first_manager_name') }}"

