---
- name: Init docker swarm
  community.docker.docker_swarm:
    state: present
  register: swarm_info

- name: Print swarm info
  debug:
    msg: "{{ swarm_info.swarm_facts.JoinTokens.Worker }}"

- name: Saving worker token to file
  local_action: copy content="{{swarm_info.swarm_facts.JoinTokens.Worker}}" dest=tmp/worker_token

- name: Print manager hostname
  debug:
    msg: "{{ groups['managers'][0] }}"
- name: Saving first manager IP to file
  local_action: copy content="{{groups['managers'][0]}}" dest=tmp/first_manager_name
